#
# Some macros
#
               
all:
	$(MAKE) -C BPL_Topology all
	$(MAKE) -C devinf all
	$(MAKE) -C getstation all
	$(MAKE) -C reset all
	$(MAKE) -C um all
	$(MAKE) -C netinf all
	$(MAKE) -C UpdateParameters all
	$(MAKE) -C RestoreFactoryDefault all
	$(MAKE) -C Pairing all
	$(MAKE) -C LinkStatistics all
	$(MAKE) -C ChangeDeviceName all
	$(MAKE) -C LocalHostsMAC all
	$(MAKE) -C Utilization all
	$(MAKE) -C PhyRateTable all

clean:
	$(MAKE) -C BPL_Topology clean
	$(MAKE) -C devinf clean
	$(MAKE) -C getstation clean
	$(MAKE) -C reset clean
	$(MAKE) -C um clean
	$(MAKE) -C netinf clean
	$(MAKE) -C UpdateParameters clean
	$(MAKE) -C RestoreFactoryDefault clean
	$(MAKE) -C Pairing clean
	$(MAKE) -C LinkStatistics clean
	$(MAKE) -C ChangeDeviceName clean
	$(MAKE) -C LocalHostsMAC clean
	$(MAKE) -C Utilization clean
	$(MAKE) -C PhyRateTable clean
